---
name: "check lint"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn lint
