name: GitHub Actions Hello World!

on:
  workflow_dispatch:
# push:
#   branches:
#     - main

jobs:
  build:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"